# Generated by Django 3.1.7 on 2021-03-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0018_auto_20210306_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Results',
        ),
        migrations.DeleteModel(
            name='Student_Login',
        ),
        migrations.DeleteModel(
            name='Teacher_Login',
        ),
        migrations.DeleteModel(
            name='Upload_Exercises',
        ),
        migrations.DeleteModel(
            name='Upload_Videos',
        ),
        migrations.DeleteModel(
            name='Watch_Videos',
        ),
    ]
