# Generated by Django 3.1.7 on 2021-03-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0021_auto_20210307_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_login',
            name='username',
            field=models.EmailField(max_length=50),
        ),
    ]
