# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0022_auto_20210307_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_login',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher_login',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
