# Generated by Django 3.1.7 on 2021-03-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0023_auto_20210307_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='caption',
        ),
        migrations.AddField(
            model_name='exercises',
            name='defenition',
            field=models.TextField(default=True, max_length=150),
        ),
        migrations.AddField(
            model_name='exercises',
            name='title',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
