# Generated by Django 3.1.7 on 2021-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0026_auto_20210307_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='defenition',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='caption',
            field=models.CharField(max_length=50),
        ),
    ]
