# Generated by Django 3.1.7 on 2021-03-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0027_auto_20210307_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='caption',
            new_name='title',
        ),
    ]
