# Generated by Django 3.1.7 on 2021-03-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0028_auto_20210307_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercises',
            old_name='date',
            new_name='deadline',
        ),
    ]
