# Generated by Django 3.1.7 on 2021-03-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0029_auto_20210307_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.DecimalField(decimal_places=0, max_digits=610399300)),
                ('date', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('score', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exercises',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
