# Generated by Django 3.1.7 on 2021-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0030_auto_20210307_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='student_login',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacher_login',
            name='username',
        ),
        migrations.AddField(
            model_name='student_login',
            name='Email',
            field=models.EmailField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='student_login',
            name='student_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AddField(
            model_name='teacher_login',
            name='Email',
            field=models.EmailField(default=False, max_length=50),
        ),
    ]
